Glitch
indieweb/blank-gh-site pull request #2
Opened 2018-08-04 14:44 UTC by jgmac1106

2018-08-04 14:51 UTC, jgmac1106 commented
making the page

2019-06-05 12:36 UTC, bueltge requested changes
This changes are not relevant for this source repository, because is a starter without private user data. So please remove this PR.

2020-05-02 02:09 UTC, tantek requested changes
I'd be ok with the About Me changes rather than My New Website, however the personal information changes (name, twitter, blog) should be removed from this PR.

2025-08-17 19:18 UTC, artlung commented
likely safe to close this PR cc: @tantek

2025-08-18 15:18 UTC, tantek requested changes
No response to request for changes, so I am closing this PR without merging.

2025-08-18 15:19 UTC, closed without merging